from __future__ import division
import motorDriver.pwm as pwm_mod
import time
import socket_class as socket
import sys
import numpy as np

speed=0.5
RMotorCh = None
LMotorCh = None

servo_min = None
servo_nut = None
servo_max = None



def pwm_setup():
    global RMotorCh,LMotorCh
    global servo_min,servo_nut,servo_max

    pwm = pwm_mod.PCA9685()
    #set frequency to 50 Hz
    pwm.set_pwm_freq(50)
    #p = 1/freq = 1/50 = 20ms
    #"tick" = 20ms / 4096 = 4.883us
    tick = 4.883

    #mim = 553us 553/4.886 = 113
    servo_min = 550/tick
    #max = 2520us 2520/4.886 = 516
    servo_max = 2550/tick
    #neuteral = 1536us 1536/4.886 = 314.47
    servo_nut = 1549/tick
    RMotorCh = 0
    LMotorCh = 2

    return pwm

def run_motors_call(pwm,R_vel, L_vel):
    """runs motors using Pi Servo hat
    receives input:
    PWM object - generated by motorDriver.py
    Right motor speed range (-1 to 1)
    left motor speed range (-1 to 1)
    """

    global RMotorCh,LMotorCh
    global servo_min,servo_nut,servo_max,speed
    
    #prevent motors from turning backwards to avoid confusing encoders 
    if R_vel < 0:
        R_vel = 0

    if L_vel < 0:
        L_vel = 0

    #ensure setup procedure was run
    if(RMotorCh is None or LMotorCh is  None):
        print("Motors not setup")
        return
    
    #calculate PWM from input
    R = int((((servo_max-servo_min)/2)*R_vel*speed+servo_nut))
    L = int((((servo_max-servo_min)/2)*-L_vel*speed+servo_nut))

    print(R,L)
    #send to hat
    pwm.set_pwm(RMotorCh,0,R)
    pwm.set_pwm(LMotorCh,0,L)


if __name__ == "__main__":
    """if this script is main it connects to a socket then passes motor values received to pi hat
       script defaults to looking for socket at 10.42.0.1 on port 50676, this can be overwritten by passing in 2 arguments
       first the IP of the server then the port to send information on"""
    #generate pwm object
    pwm = pwm_setup()
    print("Starting Test")
    
    #start socket
    s = socket.initSocket()
    
    while True:
        try:
            if len(sys.argv) == 3:
                socket.connect(s,sys.argv[1],int(sys.argv[2]))
            else:
                socket.connect(s,"10.42.0.1",50676)
            break
        except:
            pass
        
        
    while True:
        rec = s.recv(4096)
        if(rec == "stop"):
            break
        s.send("OK")
        R,L = rec.split(",")
        R = np.float32(R)
        L = np.float32(L)
        print(R,L)
        run_motors_call(pwm,R,L)
    print("Done")
